services:
  - type: web
    name: link-shortener-api
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build:api
    startCommand: node dist/apps/api/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: APP_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
